=== eduardpopa97/medical-data-parser/sistem medical/sistem medical.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT sistem_medical (pacienti,compatibilitate,medici,boli,reguli)>
<!ELEMENT pacienti (persoana+)>
<!ELEMENT persoana (nume,simptom*,grupa_sange,rh)>
<!ATTLIST nume nevoie_transfuzie CDATA #REQUIRED>
<!ATTLIST nume donator CDATA #REQUIRED>
<!ELEMENT simptom (#PCDATA)>
<!ELEMENT grupa_sange (#PCDATA)>
<!ELEMENT rh (#PCDATA)>
<!ELEMENT compatibilitate (donare+)>
<!ELEMENT donare (donator,primitor)>
<!ELEMENT donator (#PCDATA)>
<!ELEMENT primitor (#PCDATA)>
<!ELEMENT medici (medic+)>
<!ELEMENT medic (nume,specializare)>
<!ELEMENT specializare (#PCDATA)>
<!ELEMENT boli (afectiune+)>
<!ELEMENT afectiune (nume,specializare)>
<!ELEMENT reguli (regula)>
<!ELEMENT regula (if,then)>
<!ELEMENT if (simptom+)>
<!ELEMENT then (boala)>
<!ELEMENT boala (#PCDATA)>

=== eduardpopa97/medical-data-parser/sistem_expert.xml
<?xml version="1.0" standalone="no"?><?xml-stylesheet type="text/xsl" href="sistem_expert.xsl"?><!DOCTYPE sistem_medical SYSTEM "sistem medical.dtd"><!-- <sistem_medical xmlns="http://www.w3schools.com/RedsDevils" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sistem_expert.xsd"> --><sistem_medical><pacienti>	<persoana>		<nume nevoie_transfuzie="nu" donator="nu">Alexandru</nume>		<simptom>sinuzita</simptom>		<simptom>infectie_ureche</simptom>		<grupa_sange>AB</grupa_sange>		<rh>pozitiv</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="da" donator="nu">Catalin</nume>		<simptom>tuse_sange</simptom>		<simptom>oboseala</simptom>		<simptom>pierdere_greutate</simptom>		<simptom>pierdere_apetit</simptom>		<simptom>febra</simptom>		<simptom>transpiratie_abundenta</simptom>		<grupa_sange>O</grupa_sange>		<rh>negativ</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="da" donator="nu">Daniela</nume>		<simptom>durere_spate</simptom>		<simptom>urina_sange</simptom>		<simptom>dureri_stomac</simptom>		<grupa_sange>AB</grupa_sange>		<rh>negativ</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="nu">Ioana</nume>		<simptom>tuse</simptom>		<simptom>febra</simptom>		<simptom>frisoane</simptom>		<simptom>respiratie_greoaie</simptom>		<grupa_sange>A</grupa_sange>		<rh>pozitiv</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="nu">Marius</nume>		<simptom>otita</simptom>		<simptom>sinuzita</simptom>		<simptom>bronsita</simptom>		<simptom>anafilaxie_severa</simptom>		<grupa_sange>B</grupa_sange>		<rh>pozitiv</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="nu">Adrian</nume>		<simptom>bilirubina_crescuta</simptom>		<simptom>icter</simptom>		<simptom>litiaza_biliara</simptom>		<grupa_sange>O</grupa_sange>		<rh>pozitiv</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="da">Mihaela</nume>		<grupa_sange>AB</grupa_sange>		<rh>negativ</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="da">Georgiana</nume>		<grupa_sange>O</grupa_sange>		<rh>pozitiv</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="da">Paul</nume>		<grupa_sange>A</grupa_sange>		<rh>pozitiv</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="da">Cristina</nume>		<grupa_sange>B</grupa_sange>		<rh>negativ</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="da">Elena</nume>		<grupa_sange>A</grupa_sange>		<rh>negativ</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="da">Gabriel</nume>		<grupa_sange>AB</grupa_sange>		<rh>pozitiv</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="da">Adelin</nume>		<grupa_sange>O</grupa_sange>		<rh>negativ</rh>	</persoana>	<persoana>		<nume nevoie_transfuzie="nu" donator="da">Diana</nume>		<grupa_sange>B</grupa_sange>		<rh>pozitiv</rh>	</persoana></pacienti><compatibilitate>	<donare>		<donator>O</donator>		<primitor>A</primitor>	</donare>	<donare>		<donator>O</donator>		<primitor>B</primitor>	</donare>	<donare>		<donator>O</donator>		<primitor>AB</primitor>	</donare>	<donare>		<donator>O</donator>		<primitor>O</primitor>	</donare>		<donare>		<donator>A</donator>		<primitor>A</primitor>	</donare>		<donare>		<donator>A</donator>		<primitor>AB</primitor>	</donare>		<donare>		<donator>B</donator>		<primitor>AB</primitor>	</donare>		<donare>		<donator>B</donator>		<primitor>B</primitor>	</donare>	<donare>		<donator>AB</donator>		<primitor>AB</primitor>	</donare></compatibilitate><medici>	<medic>		<nume>Dr_Popescu</nume>		<specializare>boli_infectioase</specializare>	</medic>	<medic>		<nume>Dr_Zamfir</nume>		<specializare>chirurgie</specializare>	</medic>	<medic>		<nume>Dr_Marinescu</nume>		<specializare>imunologie</specializare>	</medic>	<medic>		<nume>Dr_Necula</nume>		<specializare>pneumologie</specializare>	</medic>	<medic>		<nume>Dr_Ciobanu</nume>		<specializare>nefrologie</specializare>	</medic>	<medic>		<nume>Dr_Hristache</nume>		<specializare>gastroenterologie</specializare>	</medic>	<medic>		<nume>Dr_Rizescu</nume>		<specializare>endocrinologie</specializare>	</medic></medici><boli>	<afectiune>		<nume>tuberculoza</nume>		<specializare>pneumologie</specializare>	</afectiune>	<afectiune>		<nume>pneumonie</nume>		<specializare>pneumologie</specializare>	</afectiune>	<afectiune>		<nume>pojar</nume>		<specializare>boli_infectioase</specializare>	</afectiune>	<afectiune>		<nume>gripa</nume>		<specializare>boli_infectioase</specializare>	</afectiune>	<afectiune>		<nume>infarct</nume>		<specializare>chirurgie</specializare>	</afectiune>	<afectiune>		<nume>rinita_alergica</nume>		<specializare>imunologie</specializare>	</afectiune>	<afectiune>		<nume>astm</nume>		<specializare>imunologie</specializare>	</afectiune>	<afectiune>		<nume>deficienta_imunoglobina_A</nume>		<specializare>imunologie</specializare>	</afectiune>	<afectiune>		<nume>sindrom_Cushing</nume>		<specializare>imunologie</specializare>	</afectiune>	<afectiune>		<nume>litiaza_renala</nume>		<specializare>pneumologie</specializare>	</afectiune>	<afectiune>		<nume>sindrom_Gilbert</nume>		<specializare>gastroenterologie</specializare>	</afectiune>	<afectiune>		<nume>hipertiroidism</nume>		<specializare>endocrinologie</specializare>	</afectiune>	<afectiune>		<nume>raceala</nume>		<specializare>pneumologie</specializare>	</afectiune></boli><reguli>	<regula>		<if>			<simptom>tuse_sange</simptom>			<simptom>oboseala</simptom>			<simptom>pierdere_greutate</simptom>			<simptom>pierdere_apetit</simptom>			<simptom>febra</simptom>			<simptom>transpiratie_abundenta</simptom>		</if>		<then>			<boala>tuberculoza</boala>		</then>	</regula>	<regula>		<if>			<simptom>tuse</simptom>			<simptom>febra</simptom>			<simptom>frisoane</simptom>			<simptom>respiratie_greoaie</simptom>		</if>		<then>			<boala>pneumonie</boala>		</then>	</regula>	<regula>		<if>			<simptom>febra</simptom>			<simptom>tuse</simptom>			<simptom>conjunctivita</simptom>			<simptom>eczeme</simptom>			<simptom>nas_infundat</simptom>			<simptom>durere_musculara</simptom>		</if>		<then>			<boala>pojar</boala>		</then>	</regula>	<regula>		<if>			<simptom>febra</simptom>			<simptom>durere_cap</simptom>			<simptom>frisoane</simptom>			<simptom>gat_umflat</simptom>			<simptom>nas_infundat</simptom>			<simptom>tuse</simptom>		</if>		<then>			<boala>gripa</boala>		</then>	</regula>	<regula>		<if>			<simptom>durere_piept</simptom>			<simptom>durere_musculara</simptom>			<simptom>frisoane</simptom>		</if>		<then>			<boala>infarct</boala>		</then>	</regula>	<regula>		<if>			<simptom>infectie_ureche</simptom>			<simptom>sinuzita</simptom>		</if>		<then>			<boala>rinita_alergica</boala>		</then>	</regula>	<regula>		<if>			<simptom>durere_cap</simptom>			<simptom>stranuturi</simptom>			<simptom>gat_umflat</simptom>			<simptom>nas_infundat</simptom>			<simptom>frisoane</simptom>		</if>		<then>			<boala>raceala</boala>		</then>	</regula>	<regula>		<if>			<simptom>tuse</simptom>			<simptom>durere_piept</simptom>			<simptom>respiratie_greoaie</simptom>		</if>		<then>			<boala>astm</boala>		</then>	</regula>	<regula>		<if>			<simptom>durere_spate</simptom>			<simptom>urina_sange</simptom>			<simptom>dureri_stomac</simptom>		</if>		<then>			<boala>litiaza_renala</boala>		</then>	</regula>	<regula>		<if>			<simptom>otita</simptom>			<simptom>sinuzita</simptom>			<simptom>bronsita</simptom>			<simptom>anafilaxie_severa</simptom>		</if>		<then>			<boala>deficienta_imunoglobina_A</boala>		</then>	</regula>	<regula>		<if>			<simptom>obezitate</simptom>			<simptom>durere_musculara</simptom>			<simptom>piele_uscata</simptom>			<simptom>intoleranta_glucoza</simptom>		</if>		<then>			<boala>sindrom_Cushing</boala>		</then>	</regula>	<regula>		<if>			<simptom>bilirubina_crescuta</simptom>			<simptom>icter</simptom>			<simptom>litiaza_biliara</simptom>		</if>		<then>			<boala>sindrom_Gilbert</boala>		</then>	</regula>	<regula>		<if>			<simptom>somnolenta</simptom>			<simptom>piele_uscata</simptom>			<simptom>pierdere_apetit</simptom>			<simptom>transpiratie_abundenta</simptom>		</if>		<then>			<boala>hipertiroidism</boala>		</then>	</regula></reguli></sistem_medical>
